const statesOptions = [
    {value: "Alabama", name: "Alabama"},
    {value: "Alaska", name: "Alaska"},
    {value: "Arizona", name: "Arizona"},
    {value: "Arkansas", name: "Arkansas"},
    {value: "California", name: "California"},
    {value: "Colorado", name: "Colorado"},
    {value: "Connecticut", name: "Connecticut"},
    {value: "Delaware", name: "Delaware"},
    {value: "Columbia", name: "Columbia"},
    {value: "European Union", name: "European Union"},
    {value: "Florida", name: "Florida"},
    {value: "Georgia", name: "Georgia"},
    {value: "Hawaii", name: "Hawaii"},
    {value: "Idaho", name: "Idaho"},
    {value: "Illinois", name: "Illinois"},
    {value: "Indiana", name: "Indiana"},
    {value: "Iowa", name: "Iowa"},
    {value: "Kansas", name: "Kansas"},
    {value: "Kentucky", name: "Kentucky"},
    {value: "Louisiana", name: "Louisiana"},
    {value: "Maine", name: "Maine"},
    {value: "Maryland", name: "Maryland"},
    {value: "Massachusetts", name: "Massachusetts"},
    {value: "Michigan", name: "Michigan"},
    {value: "Minnesota", name: "Minnesota"},
    {value: "Mississippi", name: "Mississippi"},
    {value: "Missouri", name: "Missouri"},
    {value: "Montana", name: "Montana"},
    {value: "Nebraska", name: "Nebraska"},
    {value: "Nevada", name: "Nevada"},
    {value: "New Hampshire", name: "New Hampshire"},
    {value: "New Jersey", name: "New Jersey"},
    {value: "New Mexico", name: "New Mexico"},
    {value: "New York", name: "New York"},
    {value: "New Carolina", name: "New Carolina"},
    {value: "North Dakota", name: "North Dakota"},
    {value: "Ohio", name: "Ohio"},
    {value: "Oklahoma", name: "Oklahoma"},
    {value: "Oregon", name: "Oregon"},
    {value: "Pennsylvania", name: "Pennsylvania"},
    {value: "Puerto Rice", name: "Puerto Rice"},
    {value: "Rhode Island", name: "Rhode Island"},
    {value: "South Carolina", name: "South Carolina"},
    {value: "South Dakota", name: "South Dakota"},
    {value: "Tennessee", name: "Tennessee"},
    {value: "Texas", name: "Texas"},
    {value: "Utah", name: "Utah"},
    {value: "Vermont", name: "Vermont"},
    {value: "Virginia", name: "Virginia"},
    {value: "Washington", name: "Washington"},
    {value: "West Virginia", name: "West Virginia"},
    {value: "Wisconsin", name: "Wisconsin"},
    {value: "Wyoming", name: "Wyoming"}
]

export default statesOptions